[package]
name = "xkcdfs"
version = "0.1.0"
authors = ["Daniel Dulaney <dan@dulaney.xyz>"]
edition = "2018"

[dependencies]
fuse = "0.3.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "*"
time = "*"
reqwest = "0.9.20"
rusqlite = "0.20"
